/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-21 16:09:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/INFOSEC/web/doan_web-ban-tui/doan_web-ban-tui/TuiXach-20210513T061631Z-001/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuiXach/WEB-INF/lib/jstl-impl.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/D:/INFOSEC/web/doan_web-ban-tui/doan_web-ban-tui/TuiXach-20210513T061631Z-001/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuiXach/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/resources/css/style.css", Long.valueOf(1590338714000L));
    _jspx_dependants.put("jar:file:/D:/INFOSEC/web/doan_web-ban-tui/doan_web-ban-tui/TuiXach-20210513T061631Z-001/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TuiXach/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1587081298000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1587081298000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Túi xinh | Trang chủ</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<style>");
      out.write(".d-flex {\n");
      out.write("  display: -webkit-box;\n");
      out.write("  display: -ms-flexbox;\n");
      out.write("  display: flex;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("  padding-bottom: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* {\n");
      out.write("  margin: 0 auto;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* a {\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* ul {\n");
      out.write("  list-style-type: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* button {\n");
      out.write("  border: none;\n");
      out.write("  border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".none {\n");
      out.write("  display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".block{\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write("#search {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#myUL {\n");
      out.write("	  position:absolute;\n");
      out.write("	  top: 40px;\n");
      out.write("	  left: 0;\n");
      out.write("  	z-index: 2;\n");
      out.write("    list-style-type: none;\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  #myUL li {\n");
      out.write("    width: 600px;\n");
      out.write("  }\n");
      out.write("  #myUL li a {\n");
      out.write("    border: 1px solid #ddd; \n");
      out.write("    margin-top: -1px;\n");
      out.write("    background-color: #fff; \n");
      out.write("    padding: 12px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-size: 15px;\n");
      out.write("    color: black;\n");
      out.write("    display: block;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  #myUL li a:hover:not(.header) {\n");
      out.write("    background-color: #eee;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	z-index: -1;\n");
      out.write("	font-family: 'Quicksand', sans-serif;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body .position {\n");
      out.write("  position: absolute;\n");
      out.write("  left: 0;\n");
      out.write("  top: 0;\n");
      out.write("  width: 100vw;\n");
      out.write("  height: 100vh;\n");
      out.write("  background: rgba(51, 51, 51, 0.753);\n");
      out.write("}\n");
      out.write("\n");
      out.write("header {\n");
      out.write("  height: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .logo {\n");
      out.write("  width: 300px;\n");
      out.write("  height: 100px;\n");
      out.write("  background: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .logo a img {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact {\n");
      out.write("  background: rgba(0, 0, 0, 0.199) url(img/backgr.png) top;\n");
      out.write("  background-blend-mode: darken;\n");
      out.write("  background-size: cover;\n");
      out.write("  width: 1200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search {\n");
      out.write("  margin: 10px;\n");
      out.write("  -webkit-box-pack: justify;\n");
      out.write("      -ms-flex-pack: justify;\n");
      out.write("          justify-content: space-between;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search {\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input {\n");
      out.write("  width: 600px;\n");
      out.write("  padding: 10px 10px 10px 50px;\n");
      out.write("  border-radius: 5px;\n");
      out.write("  border: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input::-webkit-input-placeholder {\n");
      out.write("  font-size: 13px;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input:-ms-input-placeholder {\n");
      out.write("  font-size: 13px;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input::-ms-input-placeholder {\n");
      out.write("  font-size: 13px;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input::placeholder {\n");
      out.write("  font-size: 13px;\n");
      out.write("  color: #333;\n");
      out.write("  letter-spacing: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search > input:focus {\n");
      out.write("  outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .search i {\n");
      out.write("  position: absolute;\n");
      out.write("  top: 50%;\n");
      out.write("  -webkit-transform: translateY(-50%);\n");
      out.write("          transform: translateY(-50%);\n");
      out.write("  left: 20px;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("	  \n");
      out.write("header .login_search_contact .login_search .login a {\n");
      out.write("	text-align: center;\n");
      out.write("  padding: 10px;\n");
      out.write("  margin-right: 15px;\n");
      out.write("  background: #fff;\n");
      out.write("  letter-spacing: 1px;\n");
      out.write("  border: #fff solid 1px;\n");
      out.write("  border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .login_search .login a:hover {\n");
      out.write("  background: #eebbc3;\n");
      out.write("  border: #eebbc3 solid 1px;\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("header .login_search_contact .contact {\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("  -webkit-box-pack: space-evenly;\n");
      out.write("      -ms-flex-pack: space-evenly;\n");
      out.write("          justify-content: space-evenly;\n");
      out.write("  -webkit-box-align: center;\n");
      out.write("      -ms-flex-align: center;\n");
      out.write("          align-items: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .contact i {\n");
      out.write("  padding-right: 10px;\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .contact a {\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .contact .phone_num, header .login_search_contact .contact .mail, header .login_search_contact .contact .address {\n");
      out.write("  padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .contact .phone_num:hover, header .login_search_contact .contact .mail:hover, header .login_search_contact .contact .address:hover {\n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header .login_search_contact .contact .phone_num:hover a, header .login_search_contact .contact .phone_num:hover i, header .login_search_contact .contact .mail:hover a, header .login_search_contact .contact .mail:hover i, header .login_search_contact .contact .address:hover a, header .login_search_contact .contact .address:hover i {\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title {\n");
      out.write("	\n");
      out.write("	z-index: -1;\n");
      out.write("	width: 1350px;\n");
      out.write("  -webkit-box-shadow: 1px 1px 10px 10px silver;\n");
      out.write("          box-shadow: 1px 1px 10px 10px silver;\n");
      out.write("  height: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar {\n");
      out.write("  background-color: #eebbc3;\n");
      out.write("  font-size: 20px;\n");
      out.write("  width: 1150px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul li {\n");
      out.write("  padding: 15px 60px;\n");
      out.write("  margin-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul li a, .title .navbar ul li i {\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul li:hover {\n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul li:hover > a, .title .navbar ul li:hover i {\n");
      out.write("  color: #eebbc3;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown {\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown i {\n");
      out.write("  padding-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown .menu-sh {\n");
      out.write("  display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown:hover .menu-sh {\n");
      out.write("  z-index: 1;\n");
      out.write("  -webkit-box-shadow: 1px 1px 15px 1px #2421213d;\n");
      out.write("          box-shadow: 1px 1px 15px 1px #2421213d;\n");
      out.write("  background: #eebbc3;\n");
      out.write("  color: #fff;\n");
      out.write("  position: absolute;\n");
      out.write("  left: -20px;\n");
      out.write("  top: 50px;\n");
      out.write("  width: 220px;\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown:hover .menu-sh li {\n");
      out.write("  -webkit-transform: translateX(-15%);\n");
      out.write("          transform: translateX(-15%);\n");
      out.write("  padding: 10px 18px;\n");
      out.write("  margin: 5px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown:hover .menu-sh li:hover {\n");
      out.write("  width: 100%;\n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .navbar ul .dropdown:hover .menu-sh li:hover a {\n");
      out.write("  color: #eebbc3;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .cart {\n");
      out.write("  background: #fff;\n");
      out.write("  width: 200px;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .cart a {\n");
      out.write("  font-size: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title .cart a i {\n");
      out.write("  font-size: 23px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".right {\n");
      out.write("  text-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".left {\n");
      out.write("  text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show {\n");
      out.write("  padding: 20px;\n");
      out.write("  height: 1000px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show .poster {\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show .poster img {\n");
      out.write("  width: 400px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show .poster .text h3 {\n");
      out.write("  margin: 30px 0;\n");
      out.write("  color: #ff80c0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show .poster .text p {\n");
      out.write("  width: 600px;\n");
      out.write("  color: #ff80c0;\n");
      out.write("  line-height: 25px;\n");
      out.write("  letter-spacing: 2px;\n");
      out.write("  font-weight: bold;\n");
      out.write("}\n");
      out.write(".background {\n");
      out.write("  width: 1350px;\n");
      out.write("  background: rgba(0, 0, 0, 0.199) url(img/background.jpg) top;\n");
      out.write("  background-blend-mode: darken;\n");
      out.write("  background-size: cover;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".background h1 {\n");
      out.write("  padding-top: 50px;\n");
      out.write("  color: #fff;\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".background .item {\n");
      out.write("  margin-top: 50px;\n");
      out.write("  text-align: center;\n");
      out.write("  width: 400px;\n");
      out.write("  height: 640px;\n");
      out.write("  \n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".background .item img {\n");
      out.write("  width: 350px;\n");
      out.write("  margin: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".background .item p {\n");
      out.write("  margin: 10px 25px 30px 25px;\n");
      out.write("  color: #eebbc3;\n");
      out.write("  letter-spacing: 2px;\n");
      out.write("  font-weight: bold;\n");
      out.write("  \n");
      out.write("}\n");
      out.write("\n");
      out.write(".background .item a {\n");
      out.write("  margin-top: 20px;\n");
      out.write("  background: #eebbc3;\n");
      out.write("  color: #fff;\n");
      out.write("  padding: 15px 50px;\n");
      out.write("  border: #eebbc3 solid 1px;\n");
      out.write("  border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".background .item a:hover {\n");
      out.write("  background: #fff;\n");
      out.write("  color: #eebbc3;\n");
      out.write("}\n");
      out.write(".content {\n");
      out.write("	background: #eebbc3;\n");
      out.write("	width: 1350px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .customer h1 {\n");
      out.write("  color: #333;\n");
      out.write("  margin: 60px 0 20px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .customer ul li {\n");
      out.write("  padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .customer ul li i {\n");
      out.write("  padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .customer ul li a {\n");
      out.write("  margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .customer ul li a:hover {\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write("/*# sourceMappingURL=style.css.map */");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write(" <script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write(" <script src=\"js/query.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"container d-flex\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"\">\r\n");
      out.write("                    <img src=\"img/bag.png\" alt=\"không có ảnh\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"login_search_contact\">\r\n");
      out.write("                <div class=\"login_search d-flex\">\r\n");
      out.write("                    <div class=\"search d-flex\">\r\n");
      out.write("                        <input type=\"search\" id=\"search\" onkeyup=\"myFunction()\" placeholder=\"Search for names..\">\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                        <ul id=\"myUL\" class=\"none\">\r\n");
      out.write("	                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"login d-flex\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contact d-flex\">\r\n");
      out.write("                    <div class=\"phone_num d-flex\">\r\n");
      out.write("                        <i class=\"fa fa-mobile\"></i>\r\n");
      out.write("                        <a href=\"\">+(84)538282832</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mail\">\r\n");
      out.write("                        <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                        <a href=\"https://mail.google.com/\">tad9879@gmail.com</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"address\">\r\n");
      out.write("                        <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("                        <a href=\"https://maps.google.com/\">Chỉ đường</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("        <div class=\"container d-flex\">\r\n");
      out.write("            <div class=\"navbar\">\r\n");
      out.write("                <ul class=\"d-flex\">\r\n");
      out.write("                    <li><a href=\"user/home.htm\">Trang chủ</a></li>\r\n");
      out.write("                    <li><a href=\"user/about.htm\">Thông tin</a></li>\r\n");
      out.write("                    <li class=\"dropdown d-flex\">\r\n");
      out.write("                        <a href=\"user/product.htm\">\r\n");
      out.write("                            Tất cả sản phẩm\r\n");
      out.write("                            <i class=\"fa fa-chevron-down\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"menu-sh\">\r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cart\">\r\n");
      out.write("                <a href=\"user/cart.htm?se=true\" class=\"d-flex\">\r\n");
      out.write("                    <i class=\"fa fa-cart-arrow-down\"></i>\r\n");
      out.write("                    <p>Giỏ: <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> sản phẩm</p>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"show\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"poster d-flex\">\r\n");
      out.write("                <img\r\n");
      out.write("                src=\"https://ds393qgzrxwzn.cloudfront.net/resize/m600x500/cat1/img/images/0/qxHJBOgaJZ.jpg\">\r\n");
      out.write("                \r\n");
      out.write("                    <!--src=\"https://instagram.fsgn8-1.fna.fbcdn.net/v/t51.2885-15/fr/e15/p1080x1080/91233503_2673027972984442_2431165759733253916_n.jpg?_nc_ht=instagram.fsgn8-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=LdiP4M5UsTgAX-BmBmD&oh=15d1813d3563282a30bcac19a108b608&oe=5ECFDC2A\">-->\r\n");
      out.write("                <div class=\"text right\">\r\n");
      out.write("                    <h3>HERMÈS</h3>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sequi modi, quidem sit\r\n");
      out.write("                        libero\r\n");
      out.write("                        quas voluptates dicta sed alias iusto repellendus, ex voluptatibus! Perferendis molestiae\r\n");
      out.write("                        quisquam\r\n");
      out.write("                        sint quia vero. Hic!\r\n");
      out.write("                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore commodi soluta vero sequi,\r\n");
      out.write("                        veritatis unde voluptates libero voluptatem accusamus, rem corporis optio. Quidem suscipit dicta\r\n");
      out.write("                        molestias possimus. Recusandae, officiis excepturi.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"poster d-flex\">\r\n");
      out.write("                <div class=\"text left\">\r\n");
      out.write("                    <h3>LOUIS VUITTON</h3>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sequi modi, quidem sit\r\n");
      out.write("                        libero\r\n");
      out.write("                        quas voluptates dicta sed alias iusto repellendus, ex voluptatibus! Perferendis molestiae\r\n");
      out.write("                        quisquam\r\n");
      out.write("                        sint quia vero. Hic!\r\n");
      out.write("                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore commodi soluta vero sequi,\r\n");
      out.write("                        veritatis unde voluptates libero voluptatem accusamus, rem corporis optio. Quidem suscipit dicta\r\n");
      out.write("                        molestias possimus. Recusandae, officiis excepturi.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img\r\n");
      out.write("                 src=\"https://media3.scdn.vn/img3/2019/2_18/NPhNcW_simg_de2fe0_500x500_maxb.jpg\">\r\n");
      out.write("                   <!-- src=\"https://instagram.fsgn3-1.fna.fbcdn.net/v/t51.2885-15/e35/p1080x1080/93519979_2641190519484439_4877648201690531503_n.jpg?_nc_ht=instagram.fsgn3-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=p4zoDsqVyToAX_JZtAM&oh=002acc5d1bacf0be08c957254f9a77e2&oe=5ECF19E5\">-->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"background\">\r\n");
      out.write("        <h1>Sản phẩm nổi bật</h1>\r\n");
      out.write("        <div class=\"container d-flex\">\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <img src=\"https://product.hstatic.net/1000260559/product/tui_xach_nu_da_mem_handmade__2__542481771ea1419e85439488bdd9da76_master.jpg\" alt=\"không có ảnh\">\r\n");
      out.write("                <p>Túi xách Chanel Gabrielle màu đen với thiết kế đơn giản đẹp. Màu đen mang đến cho các bạn nữ sự tự tin thoải mái khi sử dụng sản phẩm. Tên viết tắt sản phẩm: Chanel Gabrielle. Nhãn hiệu: Chanel. Sản phẩm được bán tại MiliStore với tên Túi xách Chanel Gabrielle màu đen với thiết kế đơn giản đẹp</p>\r\n");
      out.write("                <a href=\"user/product.htm\">Buy now!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <img src=\"https://www.etime.vn/upload/2016-09-10/6008-51.jpg\" alt=\"không có ảnh\">\r\n");
      out.write("                <p>Túi dạng dây đeo mạ vàng sang trọng và quý phái. - Túi xách nhỏ gọn, chất liệu da chống xước. - Màu sắc đa dạng dễ phối hợp với trang phục. - Bên trong túi rộng có nhiều ngăn tiện lợi để các vật dụng cần thiết. - Phom túi vuông vắn, bề mặt da đẹp mịn mang lại sự sang trọng, bền đẹp.</p>\r\n");
      out.write("                <a href=\"user/product.htm\">Buy now!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <img src=\"https://cdn-img-v2.webbnc.net/uploadv2/web/62/6245/product/2018/03/30/05/47/1522388254_z945141110310_de10f4404a6aa7eb28482e2990fc08ed.jpg\" alt=\"không có ảnh\">\r\n");
      out.write("                <p>Sự kết hợp hòa hảo giữa chất liệu da Monogram và da bê min màng, màu sắc đối lập. tạo nên nét phá cách sống động đầy cá tính. Vô cùng nổi bật và sành điệu mẫu Túi Xách Louis Vuitton Saintonge sẽ không làm bạn thất vọng, khi  kết hợp cùng những bộ trang phục hiện đại và cá tính.</p>\r\n");
      out.write("                <a href=\"user/product.htm\">Buy now!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- <i class=\"left-i fas fa-chevron-left\"></i>\r\n");
      out.write("            <i class=\"right-i fas fa-chevron-right\"></i> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"customer d-flex\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <h1>Hỗ trợ khách hàng</h1>\r\n");
      out.write("                    <li><i class=\"fa fa-hand-point-right\"></i><a href=\"\">Chính sách bảo hành</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-hand-point-right\"></i><a href=\"\">Chính sách đổi trả</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-hand-point-right\"></i><a href=\"\">Phương thức thanh toán</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-hand-point-right\"></i><a href=\"\">Hướng dẫn đặt hàng</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <h1>Thông tin liên hệ</h1>\r\n");
      out.write("                    <li>Địa chỉ: 97 Man Thiện, Phường Tăng Nhơn Phú A, Thành phố Thủ Đức, Thành phố Hồ Chí Minh</li>\r\n");
      out.write("                    <li>Số điện thoại: +84538282832</li>\r\n");
      out.write("                    <li>Thời gian làm việc: 8:00 - 22:00</li>\r\n");
      out.write("                    <li>Website: tuixinh123.com</li>\r\n");
      out.write("                    <li>Email: tuixinh@gmail.com</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    	<a href=\"\">\r\n");
      out.write("                    		<i class=\"fa fa-facebook\"></i>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    	<a href=\"\">\r\n");
      out.write("                    		<i class=\"fa fa-instagram\"></i>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    	<a href=\"\">\r\n");
      out.write("                    		<i class=\"fa fa-twitter\"></i>\r\n");
      out.write("                    	</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/client/home.jsp(16,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("https://code.jquery.com/jquery-3.5.1.min.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/client/home.jsp(33,25) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("t");
      // /WEB-INF/views/client/home.jsp(33,25) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                        	<li><a href=\"user/show_prod.htm?code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("	                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/client/home.jsp(39,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \r\n");
          out.write("	                    		<a href=\"user/login.htm?se=true\">Đăng nhập</a>\r\n");
          out.write("	                        	<a href=\"user/register.htm\">Đăng ký</a>\r\n");
          out.write("                        \r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/client/home.jsp(45,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \r\n");
          out.write("	                    		<a href=\"user/infor.htm\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("	                        	<a href=\"user/login.htm?se=false\">Đăng xuất</a>\r\n");
          out.write("                        \r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/client/home.jsp(82,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("t");
      // /WEB-INF/views/client/home.jsp(82,29) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product_type}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            	<li><a href=\"user/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".htm?code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
